name: "mobile"
description: "A mobile application for indoor tracking of assets."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: '3.19.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.0
  shared_preferences: ^2.0.6
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.1
  shimmer: ^2.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.0.0
  build_runner: ^2.0.0
  test: ^1.16.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/