// Mocks generated by Mockito 5.4.4 from annotations
// in mobile/test/unit/services/user_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mobile/api/user_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i2.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> signInEmailPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInEmailPassword,
          [
            email,
            password,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #signInEmailPassword,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> signUpEmailPassword(
    String? name,
    String? password,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpEmailPassword,
          [
            name,
            password,
            email,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #signUpEmailPassword,
            [
              name,
              password,
              email,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<Map<String, dynamic>> getUser(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [token],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<String> updateUserPhoto(
    String? id,
    String? photo,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPhoto,
          [
            id,
            photo,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #updateUserPhoto,
            [
              id,
              photo,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> sendEmailRedefinePassword(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailRedefinePassword,
          [email],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #sendEmailRedefinePassword,
            [email],
          ),
        )),
      ) as _i3.Future<String>);
}
