name: Build APK

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: mobile/pubspec.yaml

    - name: Install dependencies
      run: |
        cd mobile
        flutter pub get

    - name: Run tests
      run: |
        cd mobile
        flutter test --machine > tests.output

    - name: Test Reporter
      uses: dorny/test-reporter@v1.9.1
      if: always()
      with:
        name: Flutter Tests
        path: mobile/tests.output
        reporter: flutter-json
        fail-on-error: false

  build:
    name: Build APK
    runs-on: ubuntu-latest
    depends-on: tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: mobile/pubspec.yaml

    - name: Install dependencies
      run: |
        cd mobile
        flutter pub get

    - name: Build APK
      run: |
        cd mobile
        flutter build apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: Indoor Tracking APK
        path: mobile/build/app/outputs/flutter-apk/app-release.apk
