name: Integration Tests

on:
  push:
    branches:
      - main
      - development-mobile
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    environment: frontend
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.0

      - name: Clean Pub Cache
        run: |
          cd mobile
          flutter pub cache repair

      - name: Install dependencies
        run: |
          cd mobile
          flutter pub get
          flutter pub upgrade
          flutter run test
