name: Integration Tests

on:
  push:
    branches:
      - main
      - development-mobile
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test --machine > tests.output

    - name: Test Reporter
      uses: dorny/test-reporter@v1.9.1
      if: always()
      with:
        name: Flutter Tests
        path: tests.output
        reporter: flutter-json
        fail-on-error: false

    - name: Post test result as comment
      if: always()
      uses: dorny/test-reporter@v1.9.1
      with:
        name: Flutter Tests
        path: tests.output
        reporter: flutter-json
        check-name: Flutter Tests
        comment-on-pr: true
        fail-on-error: false