name: Integration Tests

on:
  push:
    branches:
      - main
      - development-mobile
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  flutter_test:
    name: Run Flutter analyze and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Get dependencies and run tests
        run: |
          cd mobile
          flutter pub get
          flutter test --coverage
          flutter test --machine > test-results.json

      - uses: dorny/test-reporter@v1.4.2
        with:
          name: test-results
          path: mobile/test-results.json
          reporter: flutter-json

      - name: Upload JUnit report
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: mobile/test-results