name: Integration Tests

on:
  push:
    branches:
      - main
      - development-mobile
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    environment: frontend
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Change directory to mobile
        run: |
          ls
          cd mobile
          ls

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests and save results
        run: |
          mkdir -p test_results
          flutter test --machine > test_results/tests.json

      - name: Convert test results to HTML
        run: |
          dart run test_reporter:main test_results/tests.json test_results/report.html

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test_results/